### ISSUE TITLE
fl defaults

### ISSUE THREAD

**Issue by rabbah** [rabbah/fl#15]
i think the default ux should be:
- copy to clipboard and terminate
- `-p` to prompt for execute (if command is "executable" by current version)
- `-y` auto execute (if command is "executable" by current version)

drop `-n` for no prompt (replaced by `-p`)

my thinking is this: if i want to execute the product command, i have to respond to the prompt with.a `y`. I might as well just type `cltr+p`. As I've used this more and more, i've been mostly either using paste or auto-exec. I've def outgrown the prompt and don't want to add `-n` on my execs.

If we were to add a config file, that could flip the `-n` default to true as well but then to get prompts back either i have to edit the config file or we need a `-p`.

**Comment by dog-f** [comment]
noted! will try to handle this offline

**Comment by rabbah** [comment]
one reason ive used paste vs prompt-y is that we arent handling some commands with `<<<` or multiline, so just punting it the handling to the shell 😅
