### ISSUE TITLE
Create GitHub action to create builds for 2-3 platforms

### ISSUE THREAD

**Issue by rabbah** [rabbah/fl#5]
Mac and linux and maybe windows

**Comment by dog-f** [comment]
Added by commits 8a68818 and c33917b

**Comment by dog-f** [comment]
- [x] exec perms
- [x] different architectures
- [x] proper naming (fl)

**Comment by dog-f** [comment]
Addressed by commits 15bbc926f5c7016f7c0768a1a1e3f0ee6d061f6c, 110c81281ecfb01ab2679ab6c2c70ef078ab2b19, and 7c46782ce0b071bd5ca5eb28ff7a7be36a9a438a
