### ISSUE TITLE
Command execution design

### ISSUE THREAD

**Issue by dog-f** [rabbah/fl#8]
There are many particularities with running commands. Golang's implementation and good understanding of privileges is important will certainly cause future rewrites if not taking advantage of the parsing measures used to avoid edge cases. I'm using this issue informally as a collection of questions/problems to consider with respect to executing commands within the tool. Should consider in-depth reading of the [golang exec library docs](https://pkg.go.dev/os/exec#Cmd.Output).

- [x] Currently cannot support single line commands separated e.g. by '&&' or ';'
- [x] Currently cannot support multi-line commands
- [x] The AI will try to generate 'ls -al' instead of 'ls -l -a', which may be fixed with contextual info (shell/environment?)
- [x] Commands like 'ls ~' or 'ls $HOME' will fail with a vague error (could be failure to retrieve env vars)
- [x]  Interactive commands! (starting processes like vim, etc...)

**Comment by rabbah** [comment]
I think `<<<` in commands also cause things to fail

**Comment by rabbah** [comment]
could separate commands into ones that are easily executable, and ones that aren't and need more work. Only offer execution for the former, instruct user to run the latter on their own.

**Comment by dog-f** [comment]
Above comments and the following are fixed by the above PR:

- Currently cannot support single line commands separated e.g. by '&&' or ';'
- Currently cannot support multi-line commands
- The AI will try to generate 'ls -al' instead of 'ls -l -a', which may be fixed with contextual info (shell/environment?)
- Commands like 'ls ~' or 'ls $HOME' will fail with a vague error (could be failure to retrieve env vars)

**Comment by dog-f** [comment]
considering interactive commands as not a priority and closing
